name: firebase
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  firebase_auth: ^4.20.0
  firebase_core: ^2.32.0
  firebase_ui_auth: ^1.14.0
  flutter:
    sdk: flutter
  weather: ^3.1.1
  firebase_messaging: ^14.9.4 
  intl: 0.18.1
  shared_preferences: ^2.2.3
  cloud_firestore: 4.17.5
 
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
