// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEtwawCrXdVNvahFeNEfwbGZtts4ygvzQ',
    appId: '1:146623002057:web:28c75eaddd17e6ded4e418',
    messagingSenderId: '146623002057',
    projectId: 'weather-forecasting-firebase',
    authDomain: 'weather-forecasting-firebase.firebaseapp.com',
    storageBucket: 'weather-forecasting-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnAppjvqpqUNGMqioFf8eq2d-QQO2ZmiU',
    appId: '1:146623002057:android:6cbc2e4f3f226ed2d4e418',
    messagingSenderId: '146623002057',
    projectId: 'weather-forecasting-firebase',
    storageBucket: 'weather-forecasting-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDWui_DGwnMiygOI1QqGpoAcY5eIeod_o',
    appId: '1:146623002057:ios:b5412c43f7927992d4e418',
    messagingSenderId: '146623002057',
    projectId: 'weather-forecasting-firebase',
    storageBucket: 'weather-forecasting-firebase.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDWui_DGwnMiygOI1QqGpoAcY5eIeod_o',
    appId: '1:146623002057:ios:b5412c43f7927992d4e418',
    messagingSenderId: '146623002057',
    projectId: 'weather-forecasting-firebase',
    storageBucket: 'weather-forecasting-firebase.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEtwawCrXdVNvahFeNEfwbGZtts4ygvzQ',
    appId: '1:146623002057:web:eaa1454944479b54d4e418',
    messagingSenderId: '146623002057',
    projectId: 'weather-forecasting-firebase',
    authDomain: 'weather-forecasting-firebase.firebaseapp.com',
    storageBucket: 'weather-forecasting-firebase.appspot.com',
  );
}
